### ISSUE TITLE
rehype-dom attributes vs rehype

### ISSUE THREAD

**Issue by Hypercubed** [syntax-tree/hast-util-to-dom#1]
Looks like `rehype-stringify` and `rehype-dom-stringify` handle element attributes inconsistently.  Looks to me that Rehype converts attributes with hyphens (i.e. `data-test`) to camel case (`dataTest`). `rehype-stringify` handles this correctly when generating the string but looks to me like `rehype-dom-stringify` is not.

See here: https://repl.it/@Hypercubed/GrubbySneakyBlogclient

**Comment by Hypercubed** [comment]
Here are relevant tests in `hast-util-to-html`: https://github.com/syntax-tree/hast-util-to-html/blob/master/test/attribute.js#L512

**Comment by kmck** [comment]
Thanks for the heads up! Fixed in https://github.com/syntax-tree/hast-util-to-dom/commit/f1f7d324df30c3ff6a2ddcc3cfaf387d87627b62
